FROM openjdk:21

ARG DEPENDENCY=build/dependency

# first layer with the external libs (i.e. the files that change the least).
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
# second layer with the 'META-INF' contents.
COPY ${DEPENDENCY}/META-INF /app/META-INF
# last layer with the application JARs (i.e. the files that change the most).
COPY ${DEPENDENCY}/BOOT-INF/classes /app

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.11.0/wait /wait
RUN chmod +x /wait

COPY --chown=spring:spring ./tests/scripts/entrypoint-spring.sh /bin/entrypoint-spring.sh
RUN chmod +x /bin/entrypoint-spring.sh

ENTRYPOINT ["/bin/entrypoint-spring.sh"]