version: "3.3"

services:
  redis:
      container_name: redis
      image: redis:alpine
      ports:
        - "6379:6379"

  spring-service:
    build:
      context: .
      dockerfile: tests/Dockerfile-spring
    depends_on:
      - redis
    environment:
      WAIT_HOSTS: redis:6379
      REDIS_ADDRESS: "redis:6379"
      CS4K_OPTION: 2

  nginx:
    container_name: nginx
    build:
      context: ..
      dockerfile: ./jvm/tests/Dockerfile-nginx
    ports:
      - "8088:8088"
    depends_on:
      - spring-service

  # Just a machine running ubuntu, with 'dig' installed so that we can observe the docker compose environment.
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: tests/Dockerfile-ubuntu
    tty: true
