version: "3.3"

services:
  # Rabbit single node
  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:alpine
    hostname: rabbit-mq1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  spring-service:
    build:
      context: .
      dockerfile: tests/Dockerfile-spring
    depends_on:
      - rabbit-mq
    environment:
      WAIT_HOSTS: rabbit-mq:5672
      RABBIT_ADDRESS: "rabbit-mq:5672"
      CS4K_OPTION: 3

  nginx:
    container_name: nginx
    build:
      context: ..
      dockerfile: jvm/tests/Dockerfile-nginx
    ports:
      - "8088:8088"
    depends_on:
      - spring-service

  # Just a machine running ubuntu, with 'dig' installed so that we can observe the docker compose environment.
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: tests/Dockerfile-ubuntu
    tty: true

networks:
  rabbitmq-cluster:
    driver: bridge
