name: Continuous Check

on:
  push:
    paths:
      ['cs4k/**']

jobs:
  build:
    name: Continuous Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build 'cs4k' with Gradle
        env:
          POSTGRESQL_DB_URL: ${{ secrets.POSTGRESQL_DB_URL }}
          REDIS_USR: ${{ secrets.REDIS_USR }}
          REDIS_PSW: ${{ secrets.REDIS_PSW }}
          REDIS_ADDRESS: ${{ vars.REDIS_ADDRESS }}
          RABBIT_USR: ${{ secrets.RABBIT_USR }}
          RABBIT_PSW: ${{ secrets.RABBIT_PSW }}
          RABBIT_ADDRESS: ${{ vars.RABBIT_ADDRESS }}
        run: ./cs4k/gradlew -p cs4k check -i