name: Continuous Check

on: [push]

jobs:
  build:
    name: Continuous Check
    runs-on: ubuntu-latest
    environment: CS4K Testing
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build 'cs4k' with Gradle
        env:
          POSTGRESQL_DB_URL: ${{ secrets.POSTGRESQL_DB_URL }}
          REDIS_USR: ${{ secrets.REDIS_USR }}
          REDIS_PSW: ${{ secrets.REDIS_PSW }}
          REDIS_ADDRESS: ${{ env.REDIS_ADDRESS }}
          RABBIT_USR: ${{ secrets.RABBIT_USR }}
          RABBIT_PSW: ${{ secrets.RABBIT_PSW }}
          RABBIT_ADDRESS: ${{ env.RABBIT_ADDRESS }}
        run: ./cs4k/gradlew -p cs4k check